---
title: "R Programming, Homework 5"
author: "Heather Deel"
date: "11/6/2019"
output: html_document
---

# Global options
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Create of figure 
## Choice 1 - creation of map showing homicides of cities in 

## Read in libraries
```{r}
library(readr)
library(sf)
library(tigris)
options(tigris_class = "sf")
options(tigris_use_cache = TRUE)
library(forcats)
library(dplyr)
library(tidyr)
library(ggplot2)
```

## Load in the data and filter to Austin, TX
```{r}
homicides <- read_csv("../data/homicide-data.csv")
homicides <- homicides %>% 
  filter(city == "Denver")
```

## Load in co data and filter to denver
```{r}
# get tx counties
co_counties <- counties(state = "CO", cb = TRUE, class = "sf")

# filter to denver county
denver_county <- co_counties %>% 
  filter(NAME == "Denver")

# tracts
denver_tracts <- tracts(state = "CO", county = "Denver", cb = TRUE, class = "sf")

```

## Convert homicides to sf object 
```{r}
# filter out lat/lon NAs
homicides <- homicides %>% 
  filter(lat != "NA") %>% 
  filter(lon != "NA")
  
# change to an sf object
homicides <- sf::st_as_sf(homicides, coords = c("lon", "lat"), crs = 4269)
  
```

## Figure generation
```{r, fig.height=7}

homicides <- homicides %>% 
  mutate(victim_race = fct_infreq(victim_race))

homicides <- homicides %>% 
  dplyr::mutate(victim_race = forcats::fct_lump(victim_race, n = 3))

# plot
ggplot() +
  geom_sf(data = denver_county) +
  geom_sf(data = denver_tracts) +
  geom_sf(data = homicides, aes(color = victim_race)) +
  facet_wrap(~disposition) +
  theme_classic() +
  ggtitle("Race of homicides in Denver County sorted by disposition") +
  labs(color = "Victim Race")
```


